# Generated by Django 5.1.1 on 2024-09-25 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='images1',
            new_name='images',
        ),
        migrations.RemoveField(
            model_name='product',
            name='images2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='images3',
        ),
    ]
