import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { getServerSession, Session } from "next-auth";
import { authOptions } from "@/utils/authOptions";
import ClientWrapper from "./components/ClientWrapper";
import { SessionProviderWrapper } from "@/components/SessionProviderWrapper";
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session: Session | null = await getServerSession(authOptions);
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="max-w-screen-2xl mx-auto">
          <SessionProviderWrapper session={session}>
            <ClientWrapper session={session} />
            {children}
          </SessionProviderWrapper>
        </div>
      </body>
    </html>
  );
}
